Need a command flag to switch between "regular" and "Monday" template...

diff --git a/bin/create b/bin/create
--- a/bin/create
+++ b/bin/create
@@ -1,19 +1,35 @@
 #!/usr/bin/env zsh
 
-if [[ $# -lt 1 ]]; then
-  echo 'error: missing argument' >&2
+function _error {
+  echo 'error: ' $1 >&2
+}
+
+function _usage {
   cat <<'USAGE'
 usage: create.sh XX--Assignment-Name
 
   create a `README.md` file in `XX--Assignment-Name/` copying the contents of
   `TEMPLATE.md`
 USAGE
+}
 
-  exit 1
+
+args=`getopt M $*`
+if [[ $? != 0 ]]; then
+  _error 'invalid argument'
+  _usage; exit 1
+fi
+set -- $args
+
+if [[ $# -lt 1 ]]; then
+  _error 'missing argument'
+  _usage; exit 1
 fi
 
+TEMPLATE=${TEMPLATE:-'TUESDAY.md'}
+
 git checkout -b $1:l \
-  && ginstall -vCD TEMPLATE.md $1/README.md \
+  && ginstall -vCD .template/$TEMPLATE $1/README.md \
   && git add $1 \
   && git status -s
 
